# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamail_tracker', '0003_journalentry_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='title',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='dreamer',
            name='phone_number',
            field=models.TextField(blank=True, default='', unique=True),
            preserve_default=False,
        ),
    ]
